# Generated by Django 5.2.14 on 2026-05-19 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код процесса')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Бизнес-процесс',
                'verbose_name_plural': 'Бизнес-процессы',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('component_type', models.CharField(choices=[('microservice', 'Микросервис'), ('module', 'Модуль'), ('batch', 'Батч'), ('legacy', 'Legacy-приложение')], max_length=30)),
                ('technical_owner', models.CharField(blank=True, max_length=100, verbose_name='Технический ответственный')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Компонент',
                'verbose_name_plural': 'Компоненты',
            },
        ),
        migrations.CreateModel(
            name='InfrastructureObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('object_type', models.CharField(choices=[('database', 'База данных'), ('message_queue', 'Очередь сообщений'), ('cache', 'Кэш'), ('storage', 'Хранилище')], max_length=30)),
                ('technology', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Инфраструктурный объект',
                'verbose_name_plural': 'Инфраструктурные объекты',
            },
        ),
        migrations.CreateModel(
            name='IntegrationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('business_purpose', models.TextField(verbose_name='Бизнес-смысл обмена')),
                ('data_schema', models.JSONField(blank=True, null=True, verbose_name='Схема данных (JSON Schema)')),
                ('data_contract_version', models.CharField(default='1.0.0', max_length=20, verbose_name='Версия контракта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Интеграционный сервис',
                'verbose_name_plural': 'Интеграционные сервисы',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название системы')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Система',
                'verbose_name_plural': 'Системы',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название команды')),
                ('slack_channel', models.CharField(blank=True, max_length=100, verbose_name='Slack канал')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='IntegrationInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Техническое имя')),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('grpc', 'gRPC'), ('kafka', 'Kafka'), ('jdbc', 'JDBC'), ('sftp', 'SFTP')], max_length=50)),
                ('method_type', models.CharField(choices=[('sync_call', 'Синхронный вызов'), ('async_message', 'Асинхронное сообщение'), ('data_read', 'Чтение данных'), ('data_write', 'Запись данных'), ('file_exchange', 'Обмен файлами'), ('stored_procedure', 'Хранимая процедура')], max_length=30)),
                ('method_detail', models.CharField(blank=True, max_length=100, verbose_name='Уточнение (GET, POST, SELECT...)')),
                ('endpoint', models.CharField(blank=True, max_length=500, verbose_name='URL, топик, путь')),
                ('environment', models.CharField(choices=[('dev', 'Разработка'), ('stage', 'Стейджинг'), ('prod', 'Продакшн')], default='prod', max_length=10, verbose_name='Среда')),
                ('technical_description', models.TextField(blank=True, verbose_name='Описание для инженеров')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_interactions', to='repository.component')),
                ('target_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_interactions', to='repository.component')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='repository.integrationservice')),
            ],
            options={
                'verbose_name': 'Интеграционное взаимодействие',
                'verbose_name_plural': 'Интеграционные взаимодействия',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название сценария')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_default', models.BooleanField(default=False, verbose_name='Основной сценарий')),
                ('business_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='repository.businessprocess')),
            ],
            options={
                'verbose_name': 'Сценарий',
                'verbose_name_plural': 'Сценарии',
            },
        ),
        migrations.AddField(
            model_name='component',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='repository.system'),
        ),
        migrations.AddField(
            model_name='system',
            name='owner_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.team', verbose_name='Команда-владелец'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='data_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.team', verbose_name='Владелец данных'),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='business_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.team', verbose_name='Бизнес-владелец'),
        ),
        migrations.CreateModel(
            name='ComponentInfrastructureLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50, verbose_name='Роль (primary_db, replica, cache)')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infra_links', to='repository.component')),
                ('infrastructure_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_links', to='repository.infrastructureobject')),
            ],
            options={
                'verbose_name': 'Связь компонента с инфраструктурой',
                'verbose_name_plural': 'Связи компонентов с инфраструктурой',
                'unique_together': {('component', 'infrastructure_object', 'role')},
            },
        ),
        migrations.CreateModel(
            name='ScenarioStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField(verbose_name='Порядок шага')),
                ('step_type', models.CharField(choices=[('ordinary', 'Обычный шаг'), ('condition', 'Ветвление')], default='ordinary', max_length=20)),
                ('condition_expression', models.TextField(blank=True, verbose_name='Условие (например, sum > 1000000)')),
                ('false_next_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='false_branch', to='repository.scenariostep', verbose_name='Переход при ЛОЖЬ')),
                ('interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='repository.integrationinteraction', verbose_name='Взаимодействие')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='repository.scenario')),
                ('true_next_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='true_branch', to='repository.scenariostep', verbose_name='Переход при ИСТИНА')),
            ],
            options={
                'verbose_name': 'Шаг сценария',
                'verbose_name_plural': 'Шаги сценария',
                'ordering': ['scenario', 'step_order'],
                'unique_together': {('scenario', 'step_order')},
            },
        ),
    ]
