# Generated by Django 5.2.14 on 2026-05-19 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
                ('color', models.CharField(default='#3b82f6', max_length=7, verbose_name='Цвет (HEX)')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AddField(
            model_name='component',
            name='created_at',
            field=models.DateTimeField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='component',
            name='updated_at',
            field=models.DateTimeField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='infrastructureobject',
            name='created_at',
            field=models.DateTimeField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='infrastructureobject',
            name='version',
            field=models.CharField(blank=True, max_length=20, verbose_name='Версия'),
        ),
        migrations.AddField(
            model_name='system',
            name='compliance_requirements',
            field=models.TextField(blank=True, verbose_name='Комплаенс'),
        ),
        migrations.AddField(
            model_name='system',
            name='created_at',
            field=models.DateTimeField(default='2024-01-01', verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='system',
            name='criticality',
            field=models.IntegerField(choices=[(1, 'Низкая'), (2, 'Средняя'), (3, 'Высокая'), (4, 'Критическая')], default=2, verbose_name='Критичность'),
        ),
        migrations.AddField(
            model_name='system',
            name='documentation_url',
            field=models.URLField(blank=True, verbose_name='Документация'),
        ),
        migrations.AddField(
            model_name='system',
            name='lifecycle_stage',
            field=models.CharField(choices=[('planned', 'Планируется'), ('development', 'В разработке'), ('production', 'В продуктивной эксплуатации'), ('deprecated', 'Устаревшая'), ('decommissioned', 'Выведена из эксплуатации')], default='development', max_length=20, verbose_name='Стадия'),
        ),
        migrations.AddField(
            model_name='system',
            name='repository_url',
            field=models.URLField(blank=True, verbose_name='Репозиторий'),
        ),
        migrations.AddField(
            model_name='system',
            name='sla_required',
            field=models.CharField(blank=True, max_length=50, verbose_name='Требуемый SLA'),
        ),
        migrations.AddField(
            model_name='system',
            name='updated_at',
            field=models.DateTimeField(default='2024-01-01', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='created_at',
            field=models.DateTimeField(default='2024-01-01', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='businessprocess',
            name='updated_at',
            field=models.DateTimeField(default='2024-01-01', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='component',
            name='technical_owner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='componentinfrastructurelink',
            name='role',
            field=models.CharField(blank=True, max_length=50, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='infrastructureobject',
            name='object_type',
            field=models.CharField(choices=[('database', 'База данных'), ('message_queue', 'Очередь сообщений'), ('cache', 'Кэш'), ('storage', 'Хранилище'), ('kafka', 'Kafka')], max_length=30),
        ),
        migrations.AlterField(
            model_name='integrationinteraction',
            name='created_at',
            field=models.DateTimeField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='integrationinteraction',
            name='endpoint',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationinteraction',
            name='environment',
            field=models.CharField(choices=[('dev', 'Разработка'), ('stage', 'Стейджинг'), ('prod', 'Продакшн')], default='prod', max_length=10),
        ),
        migrations.AlterField(
            model_name='integrationinteraction',
            name='method_detail',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='integrationinteraction',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='repository.integrationservice'),
        ),
        migrations.AlterField(
            model_name='integrationinteraction',
            name='technical_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='integrationinteraction',
            name='updated_at',
            field=models.DateTimeField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='integrationservice',
            name='created_at',
            field=models.DateTimeField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='integrationservice',
            name='data_schema',
            field=models.JSONField(blank=True, null=True, verbose_name='Схема данных'),
        ),
        migrations.AlterField(
            model_name='integrationservice',
            name='updated_at',
            field=models.DateTimeField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='scenariostep',
            name='condition_expression',
            field=models.TextField(blank=True, verbose_name='Условие'),
        ),
        migrations.AlterField(
            model_name='scenariostep',
            name='false_next_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='false_branch', to='repository.scenariostep'),
        ),
        migrations.AlterField(
            model_name='scenariostep',
            name='interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='repository.integrationinteraction'),
        ),
        migrations.AlterField(
            model_name='scenariostep',
            name='true_next_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='true_branch', to='repository.scenariostep'),
        ),
        migrations.AlterField(
            model_name='system',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='system',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='systems', to='repository.tag', verbose_name='Теги'),
        ),
    ]
