# Generated by Django 5.2.14 on 2026-05-19 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_alter_businessprocess_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='process_documents/%Y/%m/%d/', verbose_name='Файл')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('uploaded_by', models.CharField(blank=True, max_length=100, verbose_name='Кто загрузил')),
                ('business_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='repository.businessprocess')),
            ],
            options={
                'verbose_name': 'Документ процесса',
                'verbose_name_plural': 'Документы процессов',
            },
        ),
    ]
