# Generated by Django 5.2.14 on 2026-05-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_processdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprocess',
            name='business_owner',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Бизнес-владелец'),
            preserve_default=False,
        ),
    ]
