# Generated by Django 5.2.14 on 2026-05-19 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_alter_businessprocess_business_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariostep',
            name='interaction',
        ),
        migrations.RenameField(
            model_name='integrationservice',
            old_name='data_contract_version',
            new_name='version',
        ),
        migrations.AlterUniqueTogether(
            name='integrationservice',
            unique_together={('name', 'version')},
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='endpoint',
            field=models.CharField(blank=True, max_length=500, verbose_name='Endpoint / топик'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='is_deprecated',
            field=models.BooleanField(default=False, verbose_name='Устаревший'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='kafka_cluster',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kafka кластер (если применимо)'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='protocol',
            field=models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('grpc', 'gRPC'), ('kafka', 'Kafka'), ('rabbitmq', 'RabbitMQ'), ('jdbc', 'JDBC'), ('sftp', 'SFTP')], default='http', max_length=20, verbose_name='Протокол'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='request_schema',
            field=models.JSONField(blank=True, null=True, verbose_name='Схема запроса (JSON Schema)'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='response_schema',
            field=models.JSONField(blank=True, null=True, verbose_name='Схема ответа (JSON Schema)'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='schema_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на схему (AsyncAPI / OpenAPI)'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='sync_type',
            field=models.CharField(choices=[('sync', 'Синхронный (request-response)'), ('async_request', 'Асинхронный запрос'), ('async_event', 'Асинхронное событие (broadcast)')], default='sync', max_length=20, verbose_name='Тип синхронизации'),
        ),
        migrations.AlterField(
            model_name='integrationservice',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название сервиса'),
        ),
        migrations.CreateModel(
            name='IntegrationFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('dev', 'Разработка'), ('stage', 'Стейджинг'), ('prod', 'Продакшн')], default='prod', max_length=10, verbose_name='Среда')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('testing', 'Тестируется'), ('planned', 'Планируется'), ('deprecated', 'Устаревший')], default='active', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='repository.integrationservice', verbose_name='Интеграционный сервис')),
                ('source_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_flows', to='repository.system', verbose_name='Система-поставщик (источник)')),
                ('target_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_flows', to='repository.system', verbose_name='Система-потребитель')),
            ],
            options={
                'verbose_name': 'Интеграционный поток',
                'verbose_name_plural': 'Интеграционные потоки',
                'unique_together': {('service', 'source_system', 'target_system', 'environment')},
            },
        ),
        migrations.AddField(
            model_name='scenariostep',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='repository.integrationflow', verbose_name='Интеграционный поток'),
        ),
        migrations.DeleteModel(
            name='IntegrationInteraction',
        ),
        migrations.RemoveField(
            model_name='integrationservice',
            name='data_schema',
        ),
    ]
