# Generated by Django 5.2.14 on 2026-05-19 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_remove_scenariostep_interaction_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='integrationservice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='callback_endpoint',
            field=models.CharField(blank=True, max_length=500, verbose_name='Callback URL'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='owner_system',
            field=models.ForeignKey(blank=True, help_text='Система, которая определяет контракт', null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.system', verbose_name='Владелец сервиса'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='request_topic',
            field=models.CharField(blank=True, max_length=200, verbose_name='Request topic'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='response_topic',
            field=models.CharField(blank=True, max_length=200, verbose_name='Response topic'),
        ),
        migrations.AlterField(
            model_name='integrationservice',
            name='business_purpose',
            field=models.TextField(verbose_name='Бизнес-смысл'),
        ),
        migrations.AlterField(
            model_name='integrationservice',
            name='endpoint',
            field=models.CharField(blank=True, max_length=500, verbose_name='Endpoint URL'),
        ),
        migrations.AlterField(
            model_name='integrationservice',
            name='kafka_cluster',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kafka кластер'),
        ),
        migrations.AlterField(
            model_name='integrationservice',
            name='protocol',
            field=models.CharField(choices=[('http', 'HTTP Synchronous'), ('http_async', 'HTTP Asynchronous (with callback)'), ('kafka_event', 'Kafka Event (broadcast)'), ('kafka_reqresp', 'Kafka Request-Response')], max_length=20, verbose_name='Протокол'),
        ),
        migrations.AlterField(
            model_name='integrationservice',
            name='request_schema',
            field=models.JSONField(blank=True, null=True, verbose_name='Схема запроса / события'),
        ),
        migrations.AlterField(
            model_name='integrationservice',
            name='response_schema',
            field=models.JSONField(blank=True, null=True, verbose_name='Схема ответа (если есть)'),
        ),
        migrations.AlterField(
            model_name='integrationservice',
            name='version',
            field=models.CharField(default='1.0.0', max_length=20, verbose_name='Версия'),
        ),
        migrations.RemoveField(
            model_name='integrationservice',
            name='data_owner',
        ),
        migrations.RemoveField(
            model_name='integrationservice',
            name='schema_url',
        ),
        migrations.RemoveField(
            model_name='integrationservice',
            name='sync_type',
        ),
    ]
