# Generated by Django 5.2.14 on 2026-05-19 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_alter_integrationservice_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationservice',
            name='callback_endpoint',
        ),
        migrations.RemoveField(
            model_name='integrationservice',
            name='kafka_cluster',
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='cluster',
            field=models.CharField(blank=True, max_length=200, verbose_name='Кластер'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='connection_string',
            field=models.CharField(blank=True, max_length=500, verbose_name='Connection string'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='exchange',
            field=models.CharField(blank=True, max_length=200, verbose_name='Exchange'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='file_mask',
            field=models.CharField(blank=True, max_length=100, verbose_name='Маска файла'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='Путь к файлу'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='host',
            field=models.CharField(blank=True, max_length=200, verbose_name='Хост'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='message_schema',
            field=models.JSONField(blank=True, null=True, verbose_name='Схема сообщения'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='message_schema_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на схему сообщения'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='pattern',
            field=models.CharField(choices=[('reqresp', 'Запрос-ответ'), ('event', 'Событие (broadcast)'), ('db', 'Запрос к БД'), ('file', 'Файловый обмен')], default='reqresp', max_length=20, verbose_name='Паттерн'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='port',
            field=models.IntegerField(blank=True, default=22, verbose_name='Порт'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='proto_method',
            field=models.CharField(blank=True, max_length=200, verbose_name='Proto method'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='proto_schema_url',
            field=models.URLField(blank=True, verbose_name='Proto schema URL'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='proto_service',
            field=models.CharField(blank=True, max_length=200, verbose_name='Proto service'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='query',
            field=models.TextField(blank=True, verbose_name='SQL запрос'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='queue',
            field=models.CharField(blank=True, max_length=200, verbose_name='Очередь'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='request_queue',
            field=models.CharField(blank=True, max_length=200, verbose_name='Request queue'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='request_schema_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на схему запроса'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='response_queue',
            field=models.CharField(blank=True, max_length=200, verbose_name='Response queue'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='response_schema_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на схему ответа'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='routing_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='Routing key'),
        ),
        migrations.AddField(
            model_name='integrationservice',
            name='topic',
            field=models.CharField(blank=True, max_length=200, verbose_name='Топик'),
        ),
        migrations.AlterField(
            model_name='integrationservice',
            name='endpoint',
            field=models.CharField(blank=True, max_length=500, verbose_name='Endpoint'),
        ),
        migrations.AlterField(
            model_name='integrationservice',
            name='owner_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.system', verbose_name='Владелец сервиса'),
        ),
        migrations.AlterField(
            model_name='integrationservice',
            name='protocol',
            field=models.CharField(choices=[('http', 'HTTP'), ('kafka', 'Kafka'), ('mq', 'Message Queue'), ('jdbc', 'JDBC'), ('grpc', 'gRPC'), ('sftp', 'SFTP')], max_length=20, verbose_name='Протокол'),
        ),
        migrations.AlterField(
            model_name='integrationservice',
            name='request_schema',
            field=models.JSONField(blank=True, null=True, verbose_name='Схема запроса'),
        ),
        migrations.AlterField(
            model_name='integrationservice',
            name='response_schema',
            field=models.JSONField(blank=True, null=True, verbose_name='Схема ответа'),
        ),
    ]
