# Generated by Django 5.2.14 on 2026-05-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_remove_integrationservice_callback_endpoint_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scenariostep',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='scenariostep',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='scenariostep',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание шага'),
        ),
    ]
