# Generated by Django 5.2.14 on 2026-05-19 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_alter_scenariostep_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scenariostep',
            options={'ordering': ['scenario', 'step_order'], 'verbose_name': 'Шаг сценария', 'verbose_name_plural': 'Шаги сценария'},
        ),
        migrations.AlterUniqueTogether(
            name='scenariostep',
            unique_together={('scenario', 'step_order')},
        ),
        migrations.RemoveField(
            model_name='scenariostep',
            name='condition_expression',
        ),
        migrations.RemoveField(
            model_name='scenariostep',
            name='false_next_step',
        ),
        migrations.RemoveField(
            model_name='scenariostep',
            name='step_type',
        ),
        migrations.RemoveField(
            model_name='scenariostep',
            name='true_next_step',
        ),
    ]
